baseurl = "https://test.kandelvijaya.com/"
copyright = "Vijaya P. Kandel"
theme = "harbor"
disqusShortname = "kandelvijayacom"
googleAnalytics = "UA-46775685-3"
title = "Kandelvijaya"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
name = "kandelvijaya"

[outputs]
  section = ["JSON", "HTML"]


[Permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"

[Taxonomies]
    tag = "tags"

[[params.social]]
  name="twitter"
  url="https://twitter.com/kandelvijaya"
  icon="fab fa-twitter"

[[params.social]]
  name="github"
  url="https://github.com/kandelvijaya"
  icon="fab fa-github"

[[params.social]]
  name="linkedin"
  url="https://linkedin.com/kandelvijaya"
  icon="fab fa-linkedin"


[[params.nav]]
  identifier = "Home"
  name = "Home"
  icon = "fas fa-home fa-lg"
  url = "index.html"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3


[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3


[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3