baseurl = "https://test.kandelvijaya.com"
copyright = "Vijaya P. Kandel"
theme = "harbor"
disqusShortname = "kandelvijayacom"
googleAnalytics = "UA-46775685-3"
languageCode = "en-us"
title = "Kandelvijaya"

[Author]
name = "kandelvijaya"

[outputs]
  section = ["JSON", "HTML"]


# [Params]
#     mainSections = ["post"]
# github = "https://github.com/kandelvijaya"
# headline = "NSBlogging!"
# intro = true
# linkedin = "https://linkedin.com/in/kandelvijaya/"
# opengraph = true
# twitter = "https://twitter.com/kandelvijaya"

[Permalinks]
post = "/:year/:month/:day/:filename/"
[Taxonomies]
tag = "tags"

[[params.social]]
  name="twitter"
  url="https://twitter.com/kandelvijaya"
  icon="fab fa-twitter"

[[params.social]]
  name="github"
  url="https://github.com/kandelvijaya"
  icon="fab fa-github"

[[params.social]]
  name="linkedin"
  url="https://linkedin.com/kandelvijaya"
  icon="fab fa-linkedin"


[[params.nav]]
  identifier = "Home"
  name = "Home"
  icon = "fas fa-home fa-lg"
  url = "index.html"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/page/search/"
  weight = 3


[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/page/about/"
  weight = 3


[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3