baseurl = "http://kandelvijaya.com/"
title = "Kandelvijaya"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Vijaya P. Kandelvijaya"
googleAnalytics = "UA-46775685-3"
disqusShortname = "kandelvijayacom"
## PygmentsCodeFences = true
## PygmentsStyle = "monokai"

[Author]
    name = "kandelvijaya"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "NSBlogging!"
    github = "https://github.com/kandelvijaya"
    linkedin = "https://linkedin.com/in/kandelvijaya/"
    twitter = "https://twitter.com/kandelvijaya"
    opengraph = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"


# Apply this settings once the gtx page is ready
[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "GTX Monthly"
    url = "/gtxMonthly/"
    weight = 2
